<?php

use Krystal\Form\Element;
use Cms\View\Icon;
use Structure\Collection\LayoutCollection;

$layouts = (new LayoutCollection)->getAll();

?>

<div class="row">
    <div class="col-lg-7">
        <div class="card">
            <h3 class="mb-4">
                <i class="fas fa-sticky-note"></i> <?= $this->translate('Collections'); ?> <small class="text-muted">(<?= count($collections); ?>)</small>
            </h3>

            <?php $this->loadPartial('table', [
                'rows' => $collections,
                'rowAttributes' => [
                    'class' => function($row) use ($collection){
                        return $row['id'] == $collection['id'] ? 'table-info' : null;
                    }
                ],
                'columns' => [
                    ['column' => 'id', 'label' => '#'],
                    ['column' => 'name'],
                    ['column' => 'count', 'label' => 'Field count'],
                    ['column' => 'order'],
                ],
                'actions' => [
                    function($row){
                        return Icon::button(
                            'fas fa-table',
                            $this->url('Structure:Admin:Repeater@indexAction', $row['id']),
                            $this->translate('View records of this collection')
                        );
                    },

                    function($row){
                        return Icon::button(
                            'fas fa-user-edit',
                            $this->url('Structure:Admin:Field@indexAction', $row['id']),
                            $this->translate('View fields of this collection')
                        );
                    },

                    function($row){
                        return Icon::edit(
                            $this->url('Structure:Admin:Collection@editAction', $row['id']),
                            $this->translate('Edit this collection')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Structure:Admin:Collection@deleteAction', $row['id']),
                            $this->translate('Delete this collection')
                        );
                    }
                ]
            ]); ?>
        </div>
    </div>

    <div class="col-lg-5">
        <div class="card">
            <form data-group="collection" autocomplete="off">
                <h3 class="mb-4">
                    <i class="fas fa-pencil-alt"></i> <?= $this->translate(!empty($collection['id']) ? 'Edit collection' : 'Add new collection'); ?>
                </h3>

                <?= Element::hidden('collection[id]', $collection['id']); ?>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Name'); ?></label>
                    <?= Element::text('collection[name]', $collection['name'], ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Layout'); ?></label>
                    <?= Element::select('collection[layout]', $this->translateArray($layouts), $collection['layout'], ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Sorting method for items'); ?></label>
                    <?= Element::select('collection[sorting_method]', $this->translateArray($sortingOptions), $collection['sorting_method'], ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Sorting order'); ?></label>
                    <?= Element::number('collection[order]', $collection['order'], ['class' => 'form-control', 'min' => 0]); ?>
                </div>

                <?php $this->loadPartial('actions', [
                    'new' => !$collection['id'],
                    'add' => 'Structure:Admin:Collection@indexAction',
                    'edit' => [$this->url('Structure:Admin:Collection@editAction', '')],
                    'save' => 'Structure:Admin:Collection@saveAction',
                    'cancel' => 'Structure:Admin:Collection@indexAction'
                ]); ?>
            </form>
        </div>
    </div>
</div>