<?php

use Cms\View\Icon;
use Krystal\Form\Element;
use Structure\Collection\FieldTypeCollection;

$fieldTypeCollection = new FieldTypeCollection();

?>

<div class="row">
    <div class="col-lg-7">
        <div class="card">
            <h3 class="mb-4">
                <i class="far fa-clone"></i> <?= $this->translate('Fields'); ?> <small class="text-muted">(<?= count($fields); ?>)</small>
            </h3>

            <?php $this->loadPartial('table', [
                'rows' => $fields,
                'rowAttributes' => [
                    'class' => function($row) use ($field){
                        return $row['id'] == $field['id'] ? 'table-info' : null;
                    }
                ],
                'columns' => [
                    ['column' => 'id', 'label' => '#'],
                    ['column' => 'name'],
                    ['column' => 'translateable', 'translateable' => true, 'value' => function($row){
                        return boolval($row['translatable']) ? 'Yes' : 'No';
                    }],
                    ['column' => 'type', 'translateable' => true, 'value' => function($row) use ($fieldTypeCollection){
                        return $fieldTypeCollection->findByKey($row['type']);
                    }],
                    ['column' => 'order'],
                ],
                'actions' => [
                    function($row){
                        return Icon::edit(
                            $this->url('Structure:Admin:Field@editAction', $row['id']),
                            $this->translate('Edit this field')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Structure:Admin:Field@deleteAction', $row['id']),
                            $this->translate('Remove this field')
                        );
                    }
                ]
            ]); ?>
        </div>
    </div>

    <div class="col-lg-5">
        <div class="card">
            <form data-group="collection" autocomplete="off">
                <h3 class="mb-4">
                    <i class="fas fa-pencil-alt"></i> <?= $this->translate(!$field['id'] ? 'Add new field' : 'Edit the field'); ?>
                </h3>

                <?= Element::hidden('field[id]', $field['id']); ?>
                <?= Element::hidden('field[collection_id]', $field['collection_id']); ?>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Name'); ?></label>
                    <?= Element::text('field[name]', $field['name'], ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Alias'); ?></label>
                    <?= Element::text('field[alias]', $field['alias'], ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Type'); ?></label>
                    <?= Element::select('field[type]', $this->translateArray($fieldTypeCollection->getAll()), $field['type'], ['class' => 'form-control']); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Hint'); ?></label>
                    <?= Element::textarea('field[hint]', $field['hint'], ['class' => 'form-control', 'rows' => 4]); ?>
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <?= Element::checkbox('field[translatable]', $field['translatable'], ['class' => 'form-check-input', 'id' => 'input-translatable']); ?>

                        <label class="form-check-label" for="input-translatable">
                            <?= $this->translate('Translatable'); ?>
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <div class="form-check">
                        <?= Element::checkbox('field[gridable]', $field['gridable'], ['class' => 'form-check-input', 'id' => 'input-gridable']); ?>

                        <label class="form-check-label" for="input-gridable">
                            <?= $this->translate('Display in the grid'); ?>
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Sorting order'); ?></label>
                    <?= Element::number('field[order]', $field['order'], ['class' => 'form-control', 'min' => 0]); ?>
                </div>

                <?php $this->loadPartial('actions', [
                    'new' => !$field['id'],
                    'add' => [$this->url('Structure:Admin:Field@indexAction', $field['collection_id'])],
                    'edit' => [$this->url('Structure:Admin:Field@editAction', '')],
                    'save' => 'Structure:Admin:Field@saveAction',
                    'cancel' => [$this->url('Structure:Admin:Field@indexAction', $field['collection_id'])]
                ]); ?>
            </form>
        </div>
    </div>
</div>