<?php

use Cms\View\Icon;
use Krystal\Form\Element;
use Structure\Collection\FieldTypeCollection;
use Structure\View\RepeaterViewModel;

?>

<div class="row">
    <div class="col-lg-7">
        <div class="card">
            <h3 class="mb-4">
                <i class="fas fa-table"></i> <?= $this->translate('Records'); ?> <small class="text-muted">(<?= count($rows); ?>)</small>
            </h3>

            <?php $this->loadPartial('table', [
                'rows' => $rows,
                'rowAttributes' => [
                    'class' => function($row) use ($repeaterId){
                        return $row['repeater_id'] == $repeaterId ? 'table-info' : null;
                    }
                ],
                'columns' => RepeaterViewModel::createColumns($rows),
                'actions' => [
                    function($row) use ($repeater){
                        return Icon::edit(
                            $this->url('Structure:Admin:Repeater@editAction', $repeater['collection_id'], $row['repeater_id']),
                            $this->translate('Edit this record')
                        );
                    },
                    function($row){
                        return Icon::remove(
                            $this->url('Structure:Admin:Repeater@deleteAction', $row['repeater_id']),
                            $this->translate('Delete this record')
                        );
                    }
                ]
            ]); ?>
        </div>
    </div>

    <div class="col-lg-5">
        <div class="card">
            <form data-group="collection" autocomplete="off">
                <h3 class="mb-4">
                    <i class="fas fa-pencil-alt"></i> <?= $this->translate(!isset($repeater['id']) ? 'Add new record' : 'Update the record'); ?>
                </h3>

                <?= Element::hidden('repeater[id]', isset($repeater['id']) ? $repeater['id'] : null); ?>
                <?= Element::hidden('repeater[collection_id]', $repeater['collection_id']); ?>

                <?php foreach ($fields as $field): ?>
                <?php
                    $name = sprintf('record[%s]', $field['id']);
                    $attributes = ['class' => 'form-control', 'placeholder' => $field['hint']];
                ?>

                <div class="form-group">
                    <label class="control-label"><?= $field['name']; ?></label>
                    <?= Element::text($name, isset($field['value']) ? $field['value'] : null, $attributes); ?>
                </div>
                <?php endforeach; ?>

                <!-- Static attributes -->
                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Hidden'); ?></label>
                    <?= Element::checkbox('repeater[hidden]', isset($repeater['hidden']) ? $repeater['hidden'] : null); ?>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Sorting order'); ?></label>
                    <?= Element::number('repeater[order]', isset($repeater['order']) ? $repeater['order'] : null, ['class' => 'form-control']); ?>
                </div>
                <!-- ..End of static attributes -->

                <?php $this->loadPartial('actions', [
                    'new' => !$field['id'],
                    'add' => [$this->url('Structure:Admin:Repeater@addAction', $field['id'])],
                    'edit' => [$this->url('Structure:Admin:Repeater@editAction', '')],
                    'save' => 'Structure:Admin:Repeater@saveAction',
                    'cancel' => [$this->url('Structure:Admin:Repeater@indexAction', $field['collection_id'])]
                ]); ?>
            </form>
        </div>
    </div>
</div>