<?php

use Cms\View\Icon;
use Krystal\Form\Element;
use Krystal\Text\TextUtils;
use Structure\Collection\FieldTypeCollection;
use Structure\View\RepeaterViewModel;
use Structure\View\CollectionViewModel;

$columns = CollectionViewModel::getColumns($collection['layout'], $fields);

?>

<div class="row">
    <div class="<?= $columns['first']; ?>">
        <div class="card sticky-top">
            <h3 class="mb-4">
                <i class="fas fa-table"></i> <?= $this->translate('Records'); ?> <small class="text-muted">(<?= count($rows); ?>)</small>
            </h3>

            <?php $this->loadPartial('table', [
                'rows' => $rows,
                'rowAttributes' => [
                    'class' => function($row) use ($repeaterId){
                        return $row['repeater_id'] == $repeaterId ? 'table-info' : null;
                    }
                ],
                'columns' => RepeaterViewModel::createColumns($fields, $rows, $this->translate('View file')),
                'actions' => [
                    function($row) use ($repeater){
                        return Icon::edit(
                            $this->url('Structure:Admin:Repeater@editAction', $repeater['collection_id'], $row['repeater_id']),
                            $this->translate('Edit this record')
                        );
                    },
                    function($row){
                        return Icon::remove(
                            $this->url('Structure:Admin:Repeater@deleteAction', $row['repeater_id']),
                            $this->translate('Delete this record')
                        );
                    }
                ]
            ]); ?>
        </div>
    </div>

    <?php if (!empty($fields)): ?>
    <div class="<?= $columns['second']; ?>">
        <div class="card sticky-top">
            <form data-group="collection" autocomplete="off" novalidate>
                <h3 class="mb-4">
                    <i class="fas fa-pencil-alt"></i> <?= $this->translate(!isset($repeater['id']) ? 'Add new record' : 'Update the record'); ?>
                </h3>

                <?= Element::hidden('repeater[id]', isset($repeater['id']) ? $repeater['id'] : null); ?>
                <?= Element::hidden('repeater[collection_id]', $repeater['collection_id']); ?>

                <?php foreach ($fields as $field): ?>
                <?php if ($field['translatable'] == 1): ?>
                <!-- Translatable field -->
                <?php foreach ($languages as $language): ?>

                <?= Element::hidden(RepeaterViewModel::createTranslatenNs('id', $field['id'], $language->getId()), $field['id']); ?>
                <?= Element::hidden(RepeaterViewModel::createTranslatenNs('lang_id', $field['id'], $language->getId()), $language->getId()); ?>

                <?php $this->loadPartial('structure-field', [
                    'id' => $field['id'],
                    'type' => $field['type'],
                    'name' => RepeaterViewModel::createTranslatenNs('value', $field['id'], $language->getId()),
                    'delete' => RepeaterViewModel::createDeleteTranslateNs($language->getId()),
                    'label' => $field['name'] . ' / ' . $language->getName(),
                    'value' => isset($field['translations']) ? $field['translations'][$language->getId()] : null,
                    'hint' => $field['hint'],
                    'list' => FieldTypeCollection::isList($field['type']) ? TextUtils::breakString($field['hint']) : [],
                    'attributes' => [
                        'class' => 'form-control',
                        'placeholder' => $field['hint']
                    ]
                ]); ?>
                <?php endforeach; ?>

                <?php else: ?>
                <?php $this->loadPartial('structure-field', [
                    'id' => $field['id'],
                    'type' => $field['type'],
                    'name' => sprintf('record[%s]', $field['id']),
                    'delete' => RepeaterViewModel::createDeleteNs(),
                    'label' => $field['name'],
                    'value' => isset($field['value']) ? $field['value'] : null,
                    'hint' => $field['hint'],
                    'list' => FieldTypeCollection::isList($field['type']) ? TextUtils::breakString($field['hint']) : [],
                    'attributes' => [
                        'class' => 'form-control',
                        'placeholder' => $field['hint']
                    ]
                ]); ?>
                <?php endif; ?>
                <?php endforeach; ?>

                <!-- Static attributes -->
                <div class="form-group">
                    <div class="form-check">
                        <?= Element::checkbox('repeater[published]', isset($repeater['published']) ? $repeater['published'] : true, ['class' => 'form-check-input']); ?>
                        <label class="form-check-label">
                            <?= $this->translate('Published'); ?>
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label"><?= $this->translate('Sorting order'); ?></label>
                    <?= Element::number('repeater[order]', isset($repeater['order']) ? $repeater['order'] : null, ['class' => 'form-control']); ?>
                </div>
                <!-- ..End of static attributes -->

                <?php $this->loadPartial('actions', [
                    'new' => !isset($repeater['id']),
                    'add' => [$this->url('Structure:Admin:Repeater@editAction', $field['collection_id'], '')],
                    'edit' => [$this->url('Structure:Admin:Repeater@editAction', $field['collection_id'], '')],
                    'save' => 'Structure:Admin:Repeater@saveAction',
                    'cancel' => [$this->url('Structure:Admin:Repeater@indexAction', $field['collection_id'])]
                ]); ?>
            </form>
        </div>
    </div>
    <?php endif; ?>
</div>