<?php

use Cms\View\Icon;
use Krystal\Form\Element;
use Structure\Collection\FieldTypeCollection;
use Structure\View\RepeaterViewModel;

?>

<div class="row">
    <div class="col-lg-7">
        <div class="card">
            <h3 class="mb-4"><?= $this->translate('Records'); ?></h3>

            <?php $this->loadPartial('table', [
                'rows' => $rows,
                'rowAttributes' => [
                    'class' => function($row){
                        return null;
                    }
                ],
                'columns' => RepeaterViewModel::createColumns($rows),
                'actions' => [
                    function($row){
                        return Icon::edit(
                            $this->url('Structure:Admin:Repeater@editAction', $row['id']),
                            $this->translate('Edit this record')
                        );
                    },

                    function($row){
                        return Icon::remove(
                            $this->url('Structure:Admin:Repeater@deleteAction', $row['repeater_id']),
                            $this->translate('Delete this record')
                        );
                    }
                ]
            ]); ?>            
        </div>
    </div>

    <div class="col-lg-5">
        <div class="card">
            <form data-group="collection" autocomplete="off">
                <h3 class="mb-4">
                    <i class="fas fa-pencil-alt"></i> <?= $this->translate('Add new record'); ?>
                </h3>

                <?= Element::hidden('repeater[collection_id]', $id); ?>

                <?php foreach ($fields as $field): ?>
                <?php
                    $name = sprintf('record[%s]', $field['id']);
                    $attributes = ['class' => 'form-control', 'placeholder' => $field['hint']];
                ?>

                <div class="form-group">
                    <label class="control-label"><?= $field['name']; ?></label>
                    <?= Element::text($name, null, $attributes); ?>
                </div>
                <?php endforeach; ?>

                <?php $this->loadPartial('actions', [
                    'new' => !$field['id'],
                    'add' => [$this->url('Structure:Admin:Repeater@addAction', $field['id'])],
                    'edit' => [$this->url('Structure:Admin:Repeater@editAction', '')],
                    'save' => 'Structure:Admin:Repeater@saveAction',
                    'cancel' => [$this->url('Structure:Admin:Repeater@indexAction', $field['collection_id'])]
                ]); ?>
            </form>
        </div>
    </div>
</div>